In [3]:
import TweetDataFrame as TDF
import Natural_Language_Processing as NLP
from sklearn.feature_extraction.text import CountVectorizer
import tweepy as tw
import pandas as pd
import numpy as np

In [4]:
dico = pd.read_excel('dictionary_sentiment.xlsx',sheet_name=1)

In [5]:
Data = TDF.search("Airbus", "2020-12-07", 10, "en")

Authentification ok

In [6]:
Data.columns

Index(['Text', 'User', 'Date', 'Search Word'], dtype='object')

In [7]:
tweet = Data['Text'][0]

In [8]:
f= open("dict_mot/stop_words_english.txt","r")
stop_words_en=f.read().splitlines()
f.close

In [9]:
bag_of_words = pd.DataFrame()

In [10]:
for i in range(Data.shape[0]):
    tweet = Data.Text[i]
    words,BOW = NLP.bagofwords(tweet,'en', stop_words=stop_words_en, remove_non_words=False, stemming=False)
    bag_of_words = NLP.addinbow(bag_of_words,words,BOW)
bag_of_words

,airbus,cityscape,energy,feel,find,frame,gonna,hoddington,love,need,...,mission,national,open,present,presentation,prize,selected,space,student,ukseds
0,1,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,0,0,0,0,0,0,0,0,0,0
0,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0,0,0,0,0,0,0,0,0,0
0,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0,0,0,0,0,0,0,0,0,0
0,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0,0,0,0,0,0,0,0,0,0
0,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0,0,0,0,0,0,0,0,0,0
0,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0,0,0,0,0,0,0,0,0,0
0,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0,0,0,0,0,0,0,0,0,0
0,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0,0,0,0,0,0,0,0,0,0
0,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0,0,0,0,0,0,0,0,0,0
0,2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1,1,1,1,1,2,1,2,3,1

In [11]:
Data.Text[0]

'@hoddington @foxyknoxy99 That Airbus shot just feels really powerful. I love the energy in the frame.\n\nGonna need to find a place for the cityscape one.'

In [12]:
Data = TDF.search_author('CNNBusiness',20)

Authentification ok

In [13]:
Data

,Text,Author,Date
0,More than 170 prominent business leaders have ...,CNNBusiness,2021-01-05 00:34:03
1,A second round of stimulus payments are on the...,CNNBusiness,2021-01-04 23:32:03
2,"Fiat Chrysler Automobiles and Groupe PSA, the ...",CNNBusiness,2021-01-04 22:33:02
3,The results of Georgia's Senate runoffs will p...,CNNBusiness,2021-01-04 22:16:03
4,Microsoft knows there's an Xbox shortage. It's...,CNNBusiness,2021-01-04 21:41:47
5,"Haven, the health care company founded in 2018...",CNNBusiness,2021-01-04 20:29:07
6,Chipotle is adding cauliflower rice to its men...,CNNBusiness,2021-01-04 20:00:09
7,"Janet Yellen, President-elect Joe Biden's pick...",CNNBusiness,2021-01-04 19:30:06
8,McDonald's is launching new sandwiches next mo...,CNNBusiness,2021-01-04 19:00:06
9,The Dow tumbled more than 600 points around mi...,CNNBusiness,2021-01-04 17:18:41
10,Investors are gearing up for a turbocharged 20...,CNNBusiness,2021-01-04 17:08:22
11,Google workers have formed the company's first...,CNNBusiness,2021-01-04 16:01:07
12,Work-related deaths reached a 12-year high in ...,CNNBusiness,2021-01-04 13:01:08
13,A digitally created fake Queen Elizabeth II da...,CNNBusiness,2021-01-04 11:01:05
14,These robots can boogie down better than most ...,CNNBusiness,2021-01-04 09:01:13
15,"Prince Harry and Meghan, Duchess of Sussex, ha...",CNNBusiness,2021-01-04 08:01:02
16,"2020 was tough on many industries, but the aut...",CNNBusiness,2021-01-04 05:01:03
17,This California teen started a nonprofit to he...,CNNBusiness,2021-01-04 02:01:05
18,This Egyptian spa is offering snake massages h...,CNNBusiness,2021-01-04 00:01:07
19,"Beyoncé will offer $5,000 grants to help 100 p...",CNNBusiness,2021-01-03 23:01:02

In [14]:
bag_of_words = pd.DataFrame()

In [15]:
for i in range(Data.shape[0]):
    tweet = Data.Text[i]
    words,BOW = NLP.bagofwords(tweet,'en', stop_words=stop_words_en, remove_non_words=False, stemming=False)
    bag_of_words = NLP.addinbow(bag_of_words,words,BOW)
bag_of_words

,accept,biden,business,college,congress,declared,electoral,joe,leader,letter,...,crisis,due,eviction,facing,foreclosure,grant,housing,ivkquigbme,offer,people
0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,0,0,0,0,0,0,0,0,0,0
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0,0,0,0,0,0,0,0,0,0
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0,0,0,0,0,0,0,0,0,0
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0,0,0,0,0,0,0,0,0,0
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0,0,0,0,0,0,0,0,0,0
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0,0,0,0,0,0,0,0,0,0
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0,0,0,0,0,0,0,0,0,0
0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0,0,0,0,0,0,0,0,0,0
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0,0,0,0,0,0,0,0,0,0
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0,0,0,0,0,0,0,0,0,0
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0,0,0,0,0,0,0,0,0,0
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0,0,0,0,0,0,0,0,0,0
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0,0,0,0,0,0,0,0,0,0
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0,0,0,0,0,0,0,0,0,0
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0,0,0,0,0,0,0,0,0,0
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0,0,0,0,0,0,0,0,0,0
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0,0,0,0,0,0,0,0,0,0
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0,0,0,0,0,0,0,0,0,0
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0,0,0,0,0,0,0,0,0,0
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1,1,1,1,1,1,1,1,1,1

In [16]:
dataset = pd.read_csv('dataset_sentiment.csv',sep=',',encoding='latin-1',header=None,names=['sentiment','text'])

In [17]:
dataset

     sentiment                                               text
0      neutral  According to Gran , the company has no plans t...
1      neutral  Technopolis plans to develop in stages an area...
2     negative  The international electronic industry company ...
3     positive  With the new production plant the company woul...
4     positive  According to the company 's updated strategy f...
...        ...                                                ...
4841  negative  LONDON MarketWatch -- Share prices ended lower...
4842   neutral  Rinkuskiai 's beer sales fell by 6.5 per cent ...
4843  negative  Operating profit fell to EUR 35.4 mn from EUR ...
4844  negative  Net sales of the Paper segment decreased to EU...
4845  negative  Sales in Finland decreased by 10.5 % in Januar...

[4846 rows x 2 columns]

In [18]:
from sklearn.preprocessing import OrdinalEncoder
enc = OrdinalEncoder()

In [19]:
X = dataset[['text']]
y = dataset[['sentiment']]

In [20]:
y = enc.fit_transform(y)

In [21]:
y = y-1 # neutral = 0, positive = 1, negative = -1

In [22]:
# X_train,y_train = X[:int(0.2*len(X))],y[:int(0.2*len(X))] #la création du bag_of_words prend énormement de temps d'ou le 0.2 ici

In [23]:
# X_train = list(X_train['text'])

In [24]:
# bag_of_words = pd.DataFrame()
# for i in range(len(X_train)):
#     text = X_train[i]
#     words,BOW = NLP.bagofwords(text,'en', stop_words=stop_words_en, remove_non_words=False, stemming=False)
#     bag_of_words = NLP.addinbow(bag_of_words,words,BOW)
# bag_of_words

In [25]:
# y_train.shape

In [26]:
# y_train = y_train.reshape(-1)
# y_train.shape

In [27]:
# bag_of_words.shape

In [28]:
# bag_of_words_train = bag_of_words.copy()

In [29]:
from sklearn.naive_bayes import GaussianNB
from sklearn.svm import OneClassSVM
from sklearn.model_selection import cross_val_score

In [30]:
# gaussian_sentiment = GaussianNB()
# scores_gaussian = cross_val_score(gaussian_sentiment,bag_of_words_train,y_train,cv=5)

In [31]:
# scores_gaussian # moyenne 0.726

In [32]:
# svm_sentiment = OneClassSVM(kernel = 'rbf')

In [33]:
# scores_SVM = cross_val_score(svm_sentiment,bag_of_words_train,y_train,cv=5,scoring='accuracy')

In [34]:
# scores_SVM

In [35]:
from sklearn.model_selection import GridSearchCV

In [36]:
# param_grid = {'gamma':[0.1,0.01,0.5],'nu':[0.2,0.1,0.01]}

In [37]:
# svm_sentiment = OneClassSVM(kernel = 'rbf')

In [38]:
# grid_search = GridSearchCV(svm_sentiment,param_grid,cv=5,scoring='accuracy',return_train_score=True)
# grid_search.fit(bag_of_words_train,y_train)

In [39]:
# grid_search.best_score_

In [40]:
# grid_search.best_estimator_

In [41]:
# nbneu = 0
# nbpos = 0
# nbneg = 0
# for i in y_train:
#     if i == 0:
#         nbneu+=1
#     if i == 1:
#         nbpos+=1
#     if i == -1:
#         nbneg+=1
# print('neutral: ',nbneu,' positiv: ',nbpos,' negative: ',nbneu)

In [42]:
# bag_of_words_train

In [43]:
# from sklearn.model_selection import KFold
# from sklearn.metrics import confusion_matrix
# kf = KFold(n_splits=5,shuffle=True)
# for train_index,test_index in kf.split(y_train):
#     X_train_fold, X_test_fold = bag_of_words_train.iloc[train_index], bag_of_words_train.iloc[test_index]
#     y_train_fold, y_test_fold = y_train[train_index], y_train[test_index]
#     gaussian_sentiment = GaussianNB()
#     gaussian_sentiment.fit(X_train_fold,y_train_fold)
#     y_predict = gaussian_sentiment.predict(X_test_fold)
#     print(confusion_matrix(y_test_fold,y_predict,labels=[-1, 0, 1]))

Même si le GaussianNB a l'air de bien marcher on voit clairement que la sur représentation de '1' pose probème. Nous allons essayer de rééquilibrer un peu ca. Il existe plusieurs methodes, class_weight,sample_weight ou encore directement agir sur le dataframe d'entrainement

In [44]:
unique, counts = np.unique(y, return_counts=True)
print(unique,counts)

[-1.  0.  1.] [ 604 2879 1363]

In [45]:
X_train =[]
y_train =[]
k=0
i=0
while k<600:
    if y[i]==-1:
        X_train.append(X['text'][i])
        y_train.append(y[i])
        k+=1
    i+=1
k=0
i=0
while k<600:
    if y[i]==0:
        X_train.append(X['text'][i])
        y_train.append(y[i])
        k+=1
    i+=1
k=0
i=0
while k<600:
    if y[i]==1:
        X_train.append(X['text'][i])
        y_train.append(y[i])
        k+=1
    i+=1

In [46]:
import random

c = list(zip(X_train, y_train))

random.shuffle(c)

X_train, y_train = zip(*c)

X_train = list(X_train)
y_train = list(y_train)

y_train=list(np.array(y_train).reshape(-1))

In [47]:
bag_of_words_train = pd.DataFrame()
for i in range(len(X_train)):
    text = X_train[i]
    words,BOW = NLP.bagofwords(text,'en', stop_words=stop_words_en, remove_non_words=False, stemming=False)
    bag_of_words_train = NLP.addinbow(bag_of_words_train,words,BOW)
bag_of_words_train

,almost,cell,corp,doubled,earnings,global,handset,increased,maker,market,...,tecnomens,workforse,bascule,krakeroy,pile,megafon,gunneflo,formerly,replaces,rk
0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1

In [48]:
gaussian_sentiment = GaussianNB()
scores_gaussian = cross_val_score(gaussian_sentiment,bag_of_words_train,y_train,cv=5)
scores_gaussian

array([0.59722222, 0.57777778, 0.60555556, 0.59444444, 0.58333333])

In [49]:
svm_sentiment = OneClassSVM(kernel = 'rbf',gamma=0.01,nu=0.01)
scores_gaussian = cross_val_score(svm_sentiment,bag_of_words_train,y_train,cv=5,scoring='accuracy')
scores_gaussian

array([0.33333333, 0.31388889, 0.36111111, 0.33888889, 0.30555556])

In [ ]:
from sklearn.ensemble import RandomForestClassifier

In [53]:
rnd_sentiment = RandomForestClassifier(n_estimators=1000,criterion='entropy')
scores_gaussian = cross_val_score(rnd_sentiment,bag_of_words_train,y_train,cv=5,scoring='accuracy')
scores_gaussian

array([0.76944444, 0.75      , 0.77222222, 0.76666667, 0.73055556])

In [51]:
y_train = np.array(y_train)

In [52]:
from sklearn.model_selection import KFold
from sklearn.metrics import confusion_matrix
kf = KFold(n_splits=5,shuffle=True)
for train_index,test_index in kf.split(y_train):
    X_train_fold, X_test_fold = bag_of_words_train.iloc[train_index], bag_of_words_train.iloc[test_index]
    y_train_fold, y_test_fold = y_train[train_index], y_train[test_index]
    rnd_sentiment = RandomForestClassifier(n_estimators=500,criterion='entropy')
    rnd_sentiment.fit(X_train_fold,y_train_fold)
    y_predict = rnd_sentiment.predict(X_test_fold)
    print(confusion_matrix(y_test_fold,y_predict,labels=[-1, 0, 1]))

[[79 20  9]
 [ 5 92 10]
 [15 31 99]]
[[ 82  25  14]
 [  3 103  10]
 [  5  27  91]]
[[ 77  30  11]
 [  2 113  14]
 [  6  28  79]]
[[102  20   4]
 [  5 119   8]
 [  6  30  66]]
[[89 29  9]
 [ 7 99 10]
 [ 3 24 90]]

In [57]:
Data = TDF.search_author('CNNBusiness',20,remove_URL=True)

Authentification ok

In [58]:
Data

,Text,Author,Date
0,More than 170 prominent business leaders have ...,CNNBusiness,2021-01-05 00:34:03
1,A second round of stimulus payments are on the...,CNNBusiness,2021-01-04 23:32:03
2,"Fiat Chrysler Automobiles and Groupe PSA, the ...",CNNBusiness,2021-01-04 22:33:02
3,The results of Georgia's Senate runoffs will p...,CNNBusiness,2021-01-04 22:16:03
4,Microsoft knows there's an Xbox shortage. It's...,CNNBusiness,2021-01-04 21:41:47
5,"Haven, the health care company founded in 2018...",CNNBusiness,2021-01-04 20:29:07
6,Chipotle is adding cauliflower rice to its men...,CNNBusiness,2021-01-04 20:00:09
7,"Janet Yellen, President-elect Joe Biden's pick...",CNNBusiness,2021-01-04 19:30:06
8,McDonald's is launching new sandwiches next mo...,CNNBusiness,2021-01-04 19:00:06
9,The Dow tumbled more than 600 points around mi...,CNNBusiness,2021-01-04 17:18:41
10,Investors are gearing up for a turbocharged 20...,CNNBusiness,2021-01-04 17:08:22
11,Google workers have formed the company's first...,CNNBusiness,2021-01-04 16:01:07
12,Work-related deaths reached a 12-year high in ...,CNNBusiness,2021-01-04 13:01:08
13,A digitally created fake Queen Elizabeth II da...,CNNBusiness,2021-01-04 11:01:05
14,These robots can boogie down better than most ...,CNNBusiness,2021-01-04 09:01:13
15,"Prince Harry and Meghan, Duchess of Sussex, ha...",CNNBusiness,2021-01-04 08:01:02
16,"2020 was tough on many industries, but the aut...",CNNBusiness,2021-01-04 05:01:03
17,This California teen started a nonprofit to he...,CNNBusiness,2021-01-04 02:01:05
18,This Egyptian spa is offering snake massages,CNNBusiness,2021-01-04 00:01:07
19,"Beyoncé will offer $5,000 grants to help 100 p...",CNNBusiness,2021-01-03 23:01:02

In [124]:
Texte = Data['Text'][0]
Texte

'More than 170 prominent business leaders have signed a letter urging Congress to accept the Electoral College results that declared Joe Biden as the next President of the United States '

In [125]:
words,BOW = NLP.bagofwords(Texte1,'en', stop_words=stop_words_en, remove_non_words=False, stemming=False)
words

['accept',
 'biden',
 'business',
 'college',
 'congress',
 'declared',
 'electoral',
 'joe',
 'leader',
 'letter',
 'more',
 'next',
 'president',
 'prominent',
 'result',
 'signed',
 'state',
 'united',
 'urging']

In [126]:
columns = bag_of_words_train.columns

In [127]:
validation_dataframe = pd.DataFrame(columns=columns)

In [128]:
for i in range(len(words)):
    if words[i] in columns:
        validation_dataframe.loc[0,words[i]] = BOW[i]

In [129]:
validation_dataframe=validation_dataframe.fillna(0)

In [130]:
sum(validation_dataframe.loc[0])

10

In [131]:
rnd_sentiment = RandomForestClassifier(n_estimators=1000,criterion='entropy')
rnd_sentiment.fit(bag_of_words_train,y_train)

RandomForestClassifier(criterion='entropy', n_estimators=1000)

In [132]:
rnd_sentiment.predict(validation_dataframe)

array([0.])

In [133]:
Texte = Data['Text'][2]

In [134]:
words,BOW = NLP.bagofwords(Texte,'en', stop_words=stop_words_en, remove_non_words=False, stemming=False)
words

['announced',
 'automobile',
 'called',
 'car',
 'chrysler',
 'citroën',
 'combined',
 'company',
 'complete',
 'expect',
 'fiat',
 'french',
 'groupe',
 'january',
 'maker',
 'merger',
 'newly',
 'peugeot',
 'psa',
 'stellantis']

In [135]:
ind = validation_dataframe.shape[0]
for i in range(len(words)):
    if words[i] in columns:
        validation_dataframe.loc[ind,words[i]] = BOW[i]

In [137]:
validation_dataframe=validation_dataframe.fillna(0)

In [138]:
validation_dataframe

,almost,cell,corp,doubled,earnings,global,handset,increased,maker,market,...,tecnomens,workforse,bascule,krakeroy,pile,megafon,gunneflo,formerly,replaces,rk
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [139]:
rnd_sentiment.predict(validation_dataframe)

array([0., 0.])

In [143]:
Texte = Data['Text'][5]
words,BOW = NLP.bagofwords(Texte,'en', stop_words=stop_words_en, remove_non_words=False, stemming=False)
ind = validation_dataframe.shape[0]
for i in range(len(words)):
    if words[i] in columns:
        validation_dataframe.loc[ind,words[i]] = BOW[i]
validation_dataframe=validation_dataframe.fillna(0)

In [145]:
rnd_sentiment.predict(validation_dataframe)

array([ 0.,  0., -1.])